In [1]:
# import matplotlib.patches as patch
# import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy import linalg
from numpy import poly1d
# from sklearn import svm
# import tensorflow as tf
import pandas as pd
import numpy as np
import glob
import sys
import os

In [3]:
%matplotlib inline
%precision 4
plt.style.use('ggplot')
np.set_printoptions(suppress=True)

In [2]:
# Declaring Vectors

x = [1, 2, 3]
y = [4, 5, 6]

In [6]:
# print(type(x))

print("element wise addition of two vectors")
print(np.add(x,y))

print("cross product of two vectors")
print(np.cross(x,y))

print("dot product of two vectors")
print(np.dot(x,y))

element wise addition of two vectors
[5 7 9]
cross product of two vectors
[-3  6 -3]
dot product of two vectors
32


In [3]:
# initializing matrices 
x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7, 8], [9, 10]])

In [4]:
print("sum of two matrices")
print(np.add(x,y))

print("difference of two matrices")
print(np.subtract(x,y))

print("product of two matrices using np.matmul")
print(np.matmul(x,y))

print("product of two matrices using dot")
print(x.dot(y))

print("ratio of two matrices")
print(np.divide(x,y))

sum of two matrices
[[ 8 10]
 [13 15]]
difference of two matrices
[[-6 -6]
 [-5 -5]]
product of two matrices using np.matmul
[[25 28]
 [73 82]]
product of two matrices using dot
[[25 28]
 [73 82]]
ratio of two matrices
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [9]:
# Declaring matrices to test outer

x = [[1, 2, 3]]
y = [[4, 5, 6]]

print("outer product of two matrices")
print(np.outer(x,y))

outer product of two matrices
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [10]:
# Identity matrices
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# Inverses
matrix = np.matrix([[4, 1, 3], [2, 2, 5], [5, 6, 7]])
inverse = np.linalg.inv(matrix)
print(inverse)

[[ 0.3404 -0.234   0.0213]
 [-0.234  -0.2766  0.2979]
 [-0.0426  0.4043 -0.1277]]


In [17]:
# Diagnols
print(np.diag(matrix))
print(np.diag(matrix, k=2))
print(np.diag(matrix, k=1))
print(np.diag(matrix, k=-1))
print(np.diag(matrix, k=-2))

[4 2 7]
[3]
[1 5]
[2 6]
[5]


In [18]:
# trace and determinant
print(np.trace(matrix))
det = np.linalg.det(matrix)
print(det)

13
-46.99999999999999


In [25]:
# norms
x = np.array([1,2,3])

print("L1 norm of x", np.linalg.norm(x, ord=1))
print("L2 norm of x", np.linalg.norm(x, ord=2))
print("Linf norm of x", np.linalg.norm(x, ord=np.inf))

L1 norm of x 6.0
L2 norm of x 3.7416573867739413
Linf norm of x 3.0


In [29]:
# Rank of a matrix
A = np.array([[1,2,3],[2,4,6],[1,4,5]])
print("Rank of matrix A", np.linalg.matrix_rank(A))

Rank of matrix A 2


In [30]:
# Inverse of a matrix
A = np.arange(100,116).reshape(4,4)
print('the matrix A is', A)

print("The determinant of A is", np.linalg.det(A))

print("The inverse of A is", np.linalg.inv(A))

the matrix A is [[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]
The determinant of A is -2.958228394578808e-31
The inverse of A is [[ 1.0723e+14 -1.3404e+14 -5.3614e+13  8.0421e+13]
 [-1.6813e+17  3.3627e+17 -1.6813e+17  1.2286e+01]
 [ 3.3595e+17 -6.7214e+17  3.3643e+17 -2.4126e+14]
 [-1.6792e+17  3.3600e+17 -1.6824e+17  1.6084e+14]]


In [39]:
# Example of using inverse in data science

df = pd.read_csv('baseball.csv')
print(df.head())
print(df.describe())

X = df[['RS', 'RA', 'W', 'OBP','SLG','BA']]
Y = df['OOBP']

X = np.asmatrix(X)
print(X)
print(Y)

XT = np.transpose(X)

# X_XT = np.matmul(XT,X)
X_XT = XT.dot(X)

inv_X_XT = np.linalg.inv(X_XT)

# theta = np.matmul((np.matmul(inv_X_XT, XT)),Y)
theta = (inv_X_XT.dot(XT)).dot(Y)
print("theta", theta)

  Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  RankSeason  \
0  ARI     NL  2012  734  688  81  0.328  0.418  0.259         0         NaN   
1  ATL     NL  2012  700  600  94  0.320  0.389  0.247         1         4.0   
2  BAL     AL  2012  712  705  93  0.311  0.417  0.247         1         5.0   
3  BOS     AL  2012  734  806  69  0.315  0.415  0.260         0         NaN   
4  CHC     NL  2012  613  759  61  0.302  0.378  0.240         0         NaN   

   RankPlayoffs    G   OOBP   OSLG  
0           NaN  162  0.317  0.415  
1           5.0  162  0.306  0.378  
2           4.0  162  0.315  0.403  
3           NaN  162  0.331  0.428  
4           NaN  162  0.335  0.424  
              Year           RS           RA            W          OBP  \
count  1232.000000  1232.000000  1232.000000  1232.000000  1232.000000   
mean   1988.957792   715.081981   715.081981    80.904221     0.326331   
std      14.819625    91.534294    93.079933    11.458139     0.015013   
m